services:
  db:
    image: postgis/postgis:16-3.4
    container_name: postgis
    environment:
      POSTGRES_DB: roadnet
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - thaira_net 

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - thaira_net 

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/roadnet
      SECRET_KEY: "super-secret"
    volumes:
      - .:/app
    networks:
      - thaira_net 

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - thaira_net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - thaira_net      
    dns:
      - 8.8.8.8

networks:
  thaira_net:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
